version: "3.8"

name: flight-services

services:
  database:
    image: postgres:17.0
    container_name: database
    environment:
      - POSTGRES_DB=flightdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5444:5432"
    networks:
      - flight-network

  flight-api:
    image: flight-api:latest
    container_name: flight-api
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/flightdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - flight-network

networks:
  flight-network:
    driver: bridge